swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: A User object.
          schema:
            $ref: '#/definitions/User'
        400:
          description: The specified user ID is invalid (e.g. not a number).
        404:
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
definitions:
  User:
    properties:
      id:
        type: integer
      name:
        type: string
      creation:
        type: string
        format: date-time
    required:
      - id
      - name
      - creation
